services:
  backend:
    build: .
    container_name: backend-ecommerce-1
    ports:
      - "8080:8080"
    environment:
      - SPRING_MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/appDB?authSource=admin&replicaSet=rs0
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: bitnami/mongodb:latest
    container_name: backend-mongodb-1
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=replicaSetKey
      - MONGODB_ROOT_PASSWORD=rootpassword
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
    ports:
     - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 2s
      timeout: 4s
      retries: 5
      start_period: 5s
